inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-faker
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
AllCops:
  Exclude:
    - ".bundle/**/*"
    - "bin/bundle"
    - "db/**/*"
    - "node_modules/**/*"
    - "public/packs*/**/*"
    - "tmp/**/*"
    - "vendor/bundle/**/*"
  DisplayCopNames:                true
  NewCops:                        enable
  TargetRubyVersion:              3.0.0

Bundler:
  Enabled:                        true
Faker:
  Enabled:                        true
Gemspec:
  Enabled:                        true
I18n/GetText:
  Enabled:                        false
I18n/RailsI18n:
  Enabled:                        true
Layout:
  Enabled:                        true
Layout/LineLength:
  Max:                            120
  Exclude:
  - "config/initializers/devise.rb"
Lint:
  Enabled:                        true
Metrics:
  Enabled:                        true
Metrics/BlockLength:
  Max:                            60
Migration:
  Enabled:                        true
Naming:
  Enabled:                        true
Packaging:
  Enabled:                        true
Performance:
  Enabled:                        true
RSpec:
  Enabled:                        true
RSpec/Capybara:
  Enabled:                        true
RSpec/FactoryBot:
  Enabled:                        true
RSpec/Rails:
  Enabled:                        true
Rails:
  Enabled:                        true
Rake:
  Enabled:                        true
Security:
  Enabled:                        true
Style:
  Enabled:                        true
Style/Documentation:
  Enabled:                        false
Style/FrozenStringLiteralComment:
  EnforcedStyle:                  never
