development:
  adapter: redis
  url: unix:///tmp/.s.REDIS.6379

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_SOCKET") { 'unix:///tmp/.s.REDIS.6379' } %>
  channel_prefix: website_template_production
