#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

MY_NAME=$(basename "$0")

_fail() {
  ECODE=$?
  printf "~~> $MY_NAME: $NAME: aborting...\n"
  exit $ECODE
}

run_hook() {
  command=("$@")
  printf "~~> $MY_NAME: $NAME: running hook...\n"
  "${command[@]}" || _fail
  printf "~~> $MY_NAME: $NAME: hook executed successfully\n"
}

NAME="Rubocop" run_hook bundle exec rubocop
NAME="ESLint" run_hook yarn eslint .
NAME="TypeScript" run_hook yarn tsc
NAME="HAML lint" run_hook bundle exec haml-lint
NAME="Stylelint" run_hook yarn stylelint '**/*.@(sa|sc|c)ss'
NAME="I18n Health" run_hook bundle exec i18n-tasks health
NAME="RSpec" run_hook bundle exec rspec --format documentation
