name: Tests

on: [pull_request, release]

env:
  FORCE_COLOR: 1
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Setup RSpec compatible with Capybara
        run: bundle exec bin/setup
      - name: RSpec Report
        run: bundle exec rspec --force-color --format documentation
  i18n-taks:
    name: I18n Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: I18n Tasks Health
        run: bundle exec i18n-tasks health
